### ISSUE TITLE
Functionality proposals 

### ISSUE THREAD

**Issue by MarcinKosinski** [MarcinKosinski/RTCGA#1]
- Data download
- Integration of the Clinical and the Gene Expressions and the Mutations data
- Available data sets so far:

1. OV
2. BRCA
3. COAD 
4. HNSC

**Comment by MarcinKosinski** [comment]
I've created functions that enables to tell what are possible names of genes in rnaseq dataset:
````{Ruby}
#' @family RTCGA
#' @rdname availableGenesNames
#' @export
checkGenesNamesAvailability <- function( rnaseqDir, genes ){
    
    assert_that( is.character( rnaseqDir ) & length( rnaseqDir ) == 1 )
    assert_that( is.character( genes ) & length( genes ) > 0 )
    
    sapply( genes, function(element) 
        grep( pattern = element, 
              x = availableGenesNames( rnaseqDir ), 
              value = TRUE )    
    )
}

#' @family RTCGA
#' @rdname availableGenesNames
#' @export
availableGenesNames <- function( rnaseqDir ){
    
    assert_that( is.character( rnaseqDir ) & length( rnaseqDir ) == 1 )
    
    fread( rnaseqDir, select = c(1), 
           data.table = FALSE,
           colClasses = "character")[-1,1]
}
````

It looks like for: 
- OV
- BRCA
- COAD
- HNSC
there are always (for the newest release date) 20532 rows. Maybe it would be better (and faster) not to read genes' names from a `.txt` file but instead maybe there should be invisible variable containing all names of these genes?

**Comment by MarcinKosinski** [comment]
So farr all datasets are available. Most of them are available to load strictly from [`RTCGA.data`](https://github.com/mi2-warsaw/RTCGA.data) package.

Now I was thinking about some idea. There exist `RTCGA` package with functions to download, merge and integrate data. There also exists `RTCGA.data` package with the newest available `clinical` and `rna-seq` datasets. I was thinking about consistency of naming convention in RTCGA as described in this [issue](https://github.com/MarcinKosinski/RTCGA/issues/2#issuecomment-110443798) and later on on moving the rest of functions like `calculate_cooccurence` to the new package called something like `RTCGA.tools` or `RTCGA.operations` / `RTCGA.processing` / `RTCGA.algorithms` that `RTCGA` package could be finally closed and published, and any new solution or funtionality would be added to the third package from `RTCGA` family :)

What do you think about that?

**Comment by pbiecek** [comment]
So if I understand you correctly (I do not catch this 'young and vital' part ;-))
There will be three packages
-	RTCGA with functions for checking, downloading and merging data directly from broad institute
-	RTCGA.data with snapshot of newest versions of selected datasets  (clinical / rnaseq / variants / cnv)
-	RTCGA.tools (up to package name) with example analyses models / functions for data processing. This package will work either on input from RTCGA or RTCGA.data.


It's good idea to separate functionality.

**Comment by MarcinKosinski** [comment]
Yes, that's what I ment. Separation will make `RTCGA` collection easier to use.

**Comment by MarcinKosinski** [comment]
So for our past agreement.

We have 

- `RTCGA` package: for checking and downloading data directly from broad institute - on this repo
- `RTCGA.data` family with snapshots of newest version of selected datasets (so far 5: clinical / rnaseq / variants / cnv / pancan12 ) - on that repo [RTCGA.data](https://github.com/mi2-warsaw/RTCGA.data)
- `RTCGA.tools` with example analyses models / functions for data processing. This package will work either on input from **RTCGA.data** only!

Separation will make `RTCGA` collection easier to use. So I think functions for merging data should also be transported to `RTCGA.tools` and they would only work for datasets from `RTCGA.data`.

So I we will only have here

`informationTCGA`
`downloadTCGA`
`checkTCGA`
`read.clinical` - or even move this to RTCGA.tools

and we will change (that it will work with data that are in `RTCGA.data`) and transform `mergeTCGA` funtion to `RTCGA.tools`

**Comment by MarcinKosinski** [comment]
Changed `read.clinical` to `readTCGA` and I will add functionality to read `rnaseq` and `mutations` data to tidy format.
