### ISSUE TITLE
The functions' names proposals

### ISSUE THREAD

**Issue by MarcinKosinski** [MarcinKosinski/RTCGA#2]
- `mergeClinicalWithGenes` - merges a `data.frame` with a  `patient_barcode` column with a file containing genes expressions
- `mergeClinicalWithMutations` - merges a `data.frame` with a `patient_barcode` column with files containing Mutations

**Comment by MarcinKosinski** [comment]
or `mergeTCGA( clinical, mutation, genes )`

**Comment by pbiecek** [comment]
Should be easier to start with function(s) for data download
Having them it will be easier to plan names and signatures for mergers

**Comment by MarcinKosinski** [comment]
So far, there are above functions in `RTCGA`

- availableDataSets	TCGA datasets' names
- availableDates	TCGA datasets' releases dates
- availableGenesNames	TCGA genes' names and availability in 'Merge_rnaseqv2__...' dataset.
- calculate_cooccurence	Calculates coocurence matrix for given tumor
- checkDataSetsAvailability	TCGA datasets' names availability
- checkGenesNamesAvailability
- -------------------
- infoTCGA
- downloadTCGA
- mergTCGA

I suggest to merge all `available*` and `check*` functions into one `checkTCGA` function in order to maintain consistency and simplicity of naming convention. What do you think about that?

**Comment by pbiecek** [comment]
Good idea to have one function exported. 
Single function - single man page is a better entry point.
But these functions may stay as a private ones, 
the entry checkTCGA() may call them separately.

**Comment by MarcinKosinski** [comment]
Exactly, thanks for your opinion.

**Comment by MarcinKosinski** [comment]
Ok I merged those functions

- `availableDataSets` TCGA datasets' names
- `availableDates` TCGA datasets' releases dates
- `availableGenesNames` TCGA genes' names and availability in 'Merge_rnaseqv2__...' dataset.
- `checkDataSetsAvailability` TCGA datasets' names availability
- `checkGenesNamesAvailability` - -------------------

to one `checkTCGA` function

Also I transfered this `calculate_cooccurence Calculates coocurence matrix for given tumor` function to this package [https://github.com/mi2-warsaw/RTCGA.tools](https://github.com/mi2-warsaw/RTCGA.tools)

There are also those functions available in `RTCGA` package
- `infoTCGA`
- `downloadTCGA`
- `mergTCGA`
- `read.clinical`

which I think have consistant naming convention.

**Comment by MarcinKosinski** [comment]
@a5c3b65a1339147c430f3d8258d9e44b3ab41548

**Comment by pbiecek** [comment]
Now, they look better
