### ISSUE TITLE
downloadTCGA function tests

### ISSUE THREAD

**Issue by MarcinKosinski** [MarcinKosinski/RTCGA#6]
I've created `downloadTCGA ` for TCGA datasets download.
Instructions on how to install `RTCGA` package are here [https://github.com/MarcinKosinski/RTCGA/blob/master/README.md](https://github.com/MarcinKosinski/RTCGA/blob/master/README.md) or here [https://github.com/MarcinKosinski/RTCGA](https://github.com/MarcinKosinski/RTCGA). 

The examples are in package work [vignette](https://github.com/MarcinKosinski/RTCGA/blob/master/vignettes/downloadData.Rmd).

Thanks for any suggestions or bug detecion.

Function's code is here [https://github.com/MarcinKosinski/RTCGA/blob/master/R/downloadTCGA.R](https://github.com/MarcinKosinski/RTCGA/blob/master/R/downloadTCGA.R).

**Comment by MarcinKosinski** [comment]
Can you please check if this downloades files on your computer:

````{Ruby}
if (!require(devtools)) {
    install.packages("devtools")
    require(devtools)
}
install_github("MarcinKosinski/RTCGA")
library(RTCGA)
downloadTCGA( cancerTypes = c("BRCA", "COAD", "OV", "HNSC"), destDir = "data/" )
````

Sometimes it can not download file on my computer, but I am aware that I have problems with administration rights configuration on my own computer

**Comment by pbiecek** [comment]
if the directory destDir does not exist the downloadTCGA crashes
I've fixed it
also I've added few changes, code is shorter and I hope that is doing same things

**Comment by pbiecek** [comment]
there was a bug -> in whichDateToUse() avaliableDates() were not loaded properly

**Comment by MarcinKosinski** [comment]
Great, thanks for help :)

**Comment by wwojciech** [comment]
Looks like at least 2 library are required (stringi,  assertthat) to get availableDataSets() working. I have loaded it manually

**Comment by wwojciech** [comment]
Typo in function name (mergaTCGA, mergeTCGA?)?

**Comment by wwojciech** [comment]
Have you seen this http://www.compgenome.org/TCGA-Assembler/ ?

**Comment by pbiecek** [comment]
I've found this: https://wiki.nci.nih.gov/display/TCGA/RESTful+Web+Service
yesterday

What are differences and similarities between TCGA-Assembler and RTCGA?


2015-03-26 9:47 GMT+01:00 wwojciech <notifications@github.com>:

> Have you seen this http://www.compgenome.org/TCGA-Assembler/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarcinKosinski/RTCGA/issues/6#issuecomment-86406996>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
I removed `stringi` and `asserthat` packages from `RTCGA` because stringi are loaded by `rvest` and `asserthat` should be loaded when loading `dplyr`. But it looks like I was wrong :)

**Comment by MarcinKosinski** [comment]
@wwojciech  next time you can upload your suggestions via pull-request if you know where to add stuff :)

**Comment by MarcinKosinski** [comment]
Works fine for a long period of time.

**Comment by pbiecek** [comment]
Test of time, sounds like testing principle
